Repository Co-Laon/claon-admin-web, pull requests merged in 2023-03, with the labels that each got.

#1 chore: add issue and pull request templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/QUESTION.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#5 chore: 초기 세팅 next13, 스토리북, 테스트 관련 라이브러리, mui, emotion 적용
  .eslintrc.json
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  cypress.config.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  jest.config.js
  next.config.js
  package.json
  pnpm-lock.yaml
  public/favicon.ico
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Introduction.mdx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/styles/Home.module.css
  src/styles/globals.css
  tsconfig.json
Labels: chore

#6 chore: lint, prettier 적용
  .eslintrc.json
  .prettierrc.js
  next.config.js
  package.json
  pnpm-lock.yaml
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
Labels: chore, refactor

#16 chore: react-hook-form, recoil 설치
  package.json
  pnpm-lock.yaml
  src/pages/_app.tsx
Labels: chore

#17 chore: 서버 데이터 상태관리 라이브러리 react-query 추가
  package.json
  pnpm-lock.yaml
  src/pages/_app.tsx
Labels: chore

#19 chore: npmrc 파일 추가 -> peer-dependancy auto install 설정
  .npmrc
Labels: chore

#22 feat: 로그인 페이지 뷰 구현
  next.config.js
  package.json
  pnpm-lock.yaml
  src/assets/claon_login_logo.svg
  src/assets/google_login.svg
  src/assets/kakao_login.svg
  src/pages/_app.tsx
  src/pages/auth/login.tsx
  src/styles/globals.css
Labels: enhancement
