Repository Co-Laon/claon-admin-web, pull requests merged in 2023-04, with the labels that each got.

#24 refac: 가입화면 기존 래퍼 컴포넌트 레이아웃화 적용
  src/components/register/RegisterLayout.tsx
  src/pages/_app.tsx
  src/pages/register/index.tsx
Labels: refactor

#26 chore: react-query => tanstack/react-query로 변경, axios, query-key-factory 추가 및 적용
  package.json
  pnpm-lock.yaml
  src/pages/_app.tsx
  src/utils/config.ts
Labels: chore

#27 chore: 기능별 타입 정의
  src/features/Login/index.d.ts
  src/features/Register/lector.d.ts
  src/features/Register/manager.d.ts
  src/features/common/types/center.d.ts
  src/features/common/types/index.d.ts
  src/features/common/types/lector.d.ts
  src/features/common/types/profile.d.ts
Labels: chore

#32 sign-in 페이지 적용
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/features/Login/queries.ts
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/auth/login.tsx
  src/pages/index.tsx
  src/types/next-auth.d.ts
Labels: enhancement

#28 feat: api 모킹 라이브러리 적용, 구현
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/features/Register/index.d.ts
  src/features/Register/manager.d.ts
  src/features/common/types/center.d.ts
  src/mocks/adminHandlers.ts
  src/mocks/authHandlers.ts
  src/mocks/browser.ts
  src/mocks/centerHandlers.ts
  src/mocks/index.ts
  src/mocks/mockData.ts
  src/mocks/server.ts
  src/pages/_app.tsx
  src/utils/config.ts
Labels: chore, enhancement

#43 chore: change branch strategy
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/components/common/profile/ProfileButton.stories.tsx
  src/components/register/manager/SearchCenterModal.tsx
  src/components/register/manager/type.d.ts
  src/pages/register/manager/step1.tsx
Labels: chore

#44 chore: prettierignore 추가, lock.yaml 파일 코드스타일 default로 복구
  .prettierignore
  pnpm-lock.yaml
Labels: chore
